=== menit0/menito.dev/.astro/collections/resume.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "description"
      ]
    },
    "summary": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "links": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "label",
              "url"
            ]
          }
        }
      },
      "required": [
        "name",
        "title",
        "description",
        "links"
      ]
    },
    "work": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "experiences": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "place": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "url"
                ]
              },
              "icon": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            },
            "required": [
              "title",
              "date",
              "place",
              "icon",
              "description"
            ]
          }
        }
      },
      "required": [
        "name",
        "experiences"
      ]
    },
    "education": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "experiences": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "place": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "url"
                ]
              },
              "icon": {
                "type": "string"
              }
            },
            "required": [
              "title",
              "date",
              "place",
              "icon"
            ]
          }
        }
      },
      "required": [
        "name",
        "experiences"
      ]
    },
    "skills": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "items"
      ]
    },
    "mainProjects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "thumbnail": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "skills": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "name",
              "thumbnail",
              "url",
              "date",
              "description",
              "skills"
            ]
          }
        }
      },
      "required": [
        "name",
        "projects"
      ]
    },
    "sideProjects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "thumbnail": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "skills": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "name",
              "thumbnail",
              "url",
              "date",
              "description",
              "skills"
            ]
          }
        }
      },
      "required": [
        "name",
        "projects"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "metadata",
    "summary",
    "work",
    "education",
    "skills",
    "mainProjects",
    "sideProjects"
  ]
}

=== menit0/menito.dev/src/content/resume/es.json
{
  "metadata": {
    "title": "Guillermo Mena | Desarrollador Frontend",
    "description": "Desarrollador con 5+ años de experiencia profesional, especializado en desarrollo frontend con React, JavaScript y TypeScript."
  },
  "summary": {
    "name": "Guillermo Mena",
    "title": "Desarrollador Frontend de Madrid, España",
    "description": "Desarrollador con [5+ años de experiencia|violet], especializado los últimos dos años en desarrollo [frontend|orange] con [React|red], [JavaScript|amber] y [TypeScript|emerald], y con una trayectoria previa en ingeniería de videojuegos con Unity.\nTambién aplico mi experiencia en proyectos personales, donde he escalado mis propias apps en [Flutter|blue] hasta superar las 370.000 descargas a la vez que exploro nuevas tecnologías.",
    "links": [
      {
        "label": "CV",
        "url": "https://drive.proton.me/urls/JR2WYKJW1R#DCKpKistThfb"
      },
      {
        "label": "Email",
        "url": "mailto:guille.mena@protonmail.com"
      },
      {
        "label": "LinkedIn",
        "url": "https://linkedin.com/in/menito"
      },
      {
        "label": "GitHub",
        "url": "https://github.com/menit0"
      }
    ]
  },
  "work": {
    "name": "Experiencia Profesional",
    "experiences": [
      {
        "title": "Desarrollador Frontend",
        "date": "Jul 2024 - Actualidad",
        "place": {
          "name": "Sngular",
          "url": "https://linkedin.com/company/sngular"
        },
        "icon": "sngular.webp",
        "description": "Desarrollé módulos de pago y componentes escalables para el ecosistema interno de Inditex utilizando React y JavaScript. Optimicé la integración de APIs REST, garantizando la estabilidad de la plataforma mediante una arquitectura de pruebas basada en Vitest y Cypress."
      },
      {
        "title": "Desarrollador Unity",
        "date": "Jul 2022 - Jul 2024",
        "place": {
          "name": "Sngular",
          "url": "https://linkedin.com/company/sngular"
        },
        "icon": "sngular.webp",
        "description": "Lideré el desarrollo de instalaciones interactivas y experiencias VR para museos, integrando Unity con plataformas WordPress para la gestión dinámica de datos. Desarrollé herramientas internas y componentes reutilizables para automatizar flujos de trabajo y optimizar los tiempos de desarrollo."
      },
      {
        "title": "Desarrollador Unity",
        "date": "Feb 2021 - Jul 2022",
        "place": {
          "name": "Freelance",
          "url": ""
        },
        "icon": "freelance.webp",
        "description": "Desarrollé aplicaciones interactivas a medida para clientes corporativos de diversos sectores, especializándome en aplicaciones multiplataforma. Implementé espacios sociales multijugador en tiempo real utilizando Photon Engine y proporcioné soporte técnico y mantenimiento post-entrega."
      }
    ]
  },
  "education": {
    "name": "Educación",
    "experiences": [
      {
        "title": "Grado en Diseño y Desarrollo de Videojuegos",
        "date": "2014 - 2020",
        "place": {
          "name": "Universidad Rey Juan Carlos",
          "url": "https://linkedin.com/school/universidad-rey-juan-carlos/"
        },
        "icon": "urjc.webp"
      }
    ]
  },
  "skills": {
    "name": "Habilidades",
    "items": [
      "React",
      "TypeScript",
      "JavaScript",
      "Next.js",
      "Angular",
      "Astro",
      "HTML",
      "CSS",
      "Sass",
      "Tailwind CSS",
      "Redux",
      "Zustand",
      "Testing Library",
      "Vitest",
      "Jest",
      "Cypress",
      "Vite",
      "Webpack",
      "Supabase",
      "Git",
      "Jira",
      "Flutter",
      "Dart",
      "Unity",
      "C#"
    ]
  },
  "mainProjects": {
    "name": "Proyectos Principales",
    "projects": [
      {
        "name": "Inditex Back Office",
        "thumbnail": "project_inditex.webp",
        "url": "https://inditex.com",
        "date": "Jul 2024 - Present",
        "description": "Trabajé en funciones front-end e interfaces destinadas a mejorar una plataforma interna de Inditex, utilizada para gestionar todos los pagos realizados en las tiendas online de Inditex en todo el mundo.",
        "skills": [
          "React",
          "JavaScript",
          "Redux",
          "HTML",
          "Sass",
          "Vitest",
          "Cypress"
        ]
      },
      {
        "name": "Real Madrid Museum",
        "thumbnail": "project_realmadrid.webp",
        "url": "https://realmadrid.com/sites/tour-bernabeu",
        "date": "Apr 2023 - Jul 2024",
        "description": "Desarrollé experiencias interactivas y de realidad virtual para el Museo oficial del Real Madrid. Mi trabajo también se centró en crear componentes reutilizables para agilizar el trabajo de desarrollo del equipo.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Qatar Olympic and Sports Museum",
        "thumbnail": "project_qatar.webp",
        "url": "https://sngular.com/success-stories/11/faster-taller-stronger-and-more-innovative",
        "date": "Feb 2021 - Oct 2022",
        "description": "Programador principal de experiencias interactivas para el Museo Olímpico y Deportivo de Qatar. Esto incluyó minijuegos 3D, detección de movimiento con Kinect y paneles interactivos con pantallas táctiles.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "SABIC Digital Experience Center",
        "thumbnail": "project_sabic.webp",
        "url": "https://sabic.com/en",
        "date": "Oct 2022 - Apr 2023",
        "description": "Programador principal de interactivos multidispositivo para la sede central de SABIC, una empresa líder en la industria química, incluyendo mesas interactivas, pantallas táctiles y experiencias de realidad aumentada.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Exhibify",
        "thumbnail": "project_exhibify.webp",
        "url": "https://exhibify.net",
        "date": "Aug 2021 - Mar 2022",
        "description": "Desarrollé una herramienta de creación de exposiciones virtuales para Exhibify, una plataforma que permite a los artistas crear exposiciones personalizadas para mostrar y vender su trabajo.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Color Rush",
        "thumbnail": "project_naolito.webp",
        "url": "https://naolito.com",
        "date": "May 2022 - Jul 2022",
        "description": "Desarrollé un prototipo de juego móvil de tipo runner 2D encargado por Naolito Animation Studios, que incluía todas las mecánicas principales y un editor de niveles para facilitar la creación de nuevos niveles por parte del equipo de Naolito.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Uttopion",
        "thumbnail": "project_uttopion.webp",
        "url": "https://uttopion.es",
        "date": "Feb 2021 - Dec 2021",
        "description": "Trabajé en la incorporación de funciones multijugador y actualizaciones de contenido para Uttopion, un metaverso virtual donde los usuarios pueden asistir a conciertos, fiestas y otros eventos en un entorno 3D.",
        "skills": ["Unity", "C#", "Photon"]
      },
      {
        "name": "TodoLibros3D",
        "thumbnail": "project_todolibros3d.webp",
        "url": "https://todolibros3d.com",
        "date": "Feb 2022 - Mar 2022",
        "description": "Añadí funciones multijugador a TodoLibros3D, una librería virtual en 3D donde ahora los usuarios podrían interactuar entre ellos creando sus propios avatares personalizados y mediante un chat de texto.",
        "skills": ["Unity", "C#", "Photon"]
      }
    ]
  },
  "sideProjects": {
    "name": "Proyectos Personales",
    "projects": [
      {
        "name": "GameResources.dev",
        "thumbnail": "project_gameresources.webp",
        "url": "https://gameresources.dev",
        "date": "2026",
        "description": "Un directorio de herramientas y recursos útiles para cada campo que envuelve el desarrollo de videojuegos, incluyendo código, 3D assets, marketing o sonido.",
        "skills": ["Astro", "TypeScript", "HTML", "CSS"]
      },
      {
        "name": "WattLuz",
        "thumbnail": "project_wattluz.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.precioluz",
        "date": "2024",
        "description": "Aplicación móvil para consultar el precio de la luz en España, con gráficos interactivos y notificaciones personalizables para ayudarte a ahorrar en tu factura de la electricidad.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Nanito Launcher",
        "thumbnail": "project_nanitolauncher.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.minimallauncher",
        "date": "2024",
        "description": "Launcher minimalista para Android que ofrece una experiencia sin distracciones para mejorar la productividad, con un diseño limpio y una interfaz personalizable.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Chupito",
        "thumbnail": "project_chupito.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.appcohol",
        "date": "2020",
        "description": "Aplicación móvil que incluye retos y preguntas para animar cualquier fiesta. Con más de 370.000 descargas, se ha convertido en una de las apps más populares en su categoría en varios países.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Pincho.io",
        "thumbnail": "project_pinchoio.webp",
        "url": "https://youtube.com/watch?v=eDQVwSZA6f0",
        "date": "2019",
        "description": "Juego móvil inspirado en Agar.io, donde los jugadores deben atacar a otros para crecer y ser el más grande de la partida. El juego alcanzó +5.000 descargas en Google Play, pero actualmente ya no está disponible.",
        "skills": ["Unity", "C#"]
      }
    ]
  }
}

=== menit0/menito.dev/src/content/resume/en.json
{
  "metadata": {
    "title": "Guillermo Mena | Frontend Developer",
    "description": "Developer with 5+ years of professional experience, specializing in frontend development with React, JavaScript and TypeScript."
  },
  "summary": {
    "name": "Guillermo Mena",
    "title": "Frontend Developer from Madrid, Spain",
    "description": "Developer with [5+ years of experience|violet], specializing for the past two years in [frontend|orange] development with [React|red], [JavaScript|amber] and [TypeScript|emerald], and with previous experience in game engineering with Unity.\nI also apply my expertise to indie projects, where I've scaled my own [Flutter|blue] apps to 370,000+ downloads while experimenting with a broad range of other technologies.",
    "links": [
      {
        "label": "CV",
        "url": "https://drive.proton.me/urls/MWPD5ASFMM#dHGSHgOjK4xK"
      },
      {
        "label": "Email",
        "url": "mailto:guille.mena@protonmail.com"
      },
      {
        "label": "LinkedIn",
        "url": "https://linkedin.com/in/menito"
      },
      {
        "label": "GitHub",
        "url": "https://github.com/menit0"
      }
    ]
  },
  "work": {
    "name": "Work Experience",
    "experiences": [
      {
        "title": "Frontend Developer",
        "date": "Jul 2024 - Present",
        "place": {
          "name": "Sngular",
          "url": "https://linkedin.com/company/sngular"
        },
        "icon": "sngular.webp",
        "description": "Engineered payment modules and scalable UI components for Inditex's internal ecosystem using React and JavaScript. Optimized the integration of REST APIs while ensuring platform stability through a testing architecture based on Vitest and Cypress."
      },
      {
        "title": "Unity Developer",
        "date": "Jul 2022 - Jul 2024",
        "place": {
          "name": "Sngular",
          "url": "https://linkedin.com/company/sngular"
        },
        "icon": "sngular.webp",
        "description": "Led the development of immersive VR and interactive museum installations, integrating Unity with headless WordPress architectures for dynamic data management. Built internal tools and reusable components to automate workflows and streamline development."
      },
      {
        "title": "Unity Developer",
        "date": "Feb 2021 - Jul 2022",
        "place": {
          "name": "Freelance",
          "url": ""
        },
        "icon": "freelance.webp",
        "description": "Delivered interactive applications for enterprise clients across various sectors, specializing in high-performance multiplatform applications. Engineered real-time multiplayer social spaces using Photon Engine and provided post-delivery technical support and maintenance."
      }
    ]
  },
  "education": {
    "name": "Education",
    "experiences": [
      {
        "title": "Degree in Video Game Development and Design",
        "date": "2014 - 2020",
        "place": {
          "name": "Rey Juan Carlos University",
          "url": "https://linkedin.com/school/universidad-rey-juan-carlos/"
        },
        "icon": "urjc.webp"
      }
    ]
  },
  "skills": {
    "name": "Skills",
    "items": [
      "React",
      "TypeScript",
      "JavaScript",
      "Next.js",
      "Angular",
      "Astro",
      "HTML",
      "CSS",
      "Sass",
      "Tailwind CSS",
      "Redux",
      "Zustand",
      "Testing Library",
      "Vitest",
      "Jest",
      "Cypress",
      "Vite",
      "Webpack",
      "Supabase",
      "Git",
      "Jira",
      "Flutter",
      "Dart",
      "Unity",
      "C#"
    ]
  },
  "mainProjects": {
    "name": "Main Projects",
    "projects": [
      {
        "name": "Inditex Back Office",
        "thumbnail": "project_inditex.webp",
        "url": "https://inditex.com",
        "date": "Jul 2024 - Present",
        "description": "Worked on front-end features and interfaces aimed to improve an Inditex internal platform, used to manage all payments made in Inditex online stores worldwide.",
        "skills": [
          "React",
          "JavaScript",
          "Redux",
          "HTML",
          "Sass",
          "Vitest",
          "Cypress"
        ]
      },
      {
        "name": "Real Madrid Museum",
        "thumbnail": "project_realmadrid.webp",
        "url": "https://realmadrid.com/sites/tour-bernabeu",
        "date": "Apr 2023 - Jul 2024",
        "description": "Developed interactives and VR experiences for the official Real Madrid Museum. My work also focused on create reusable components to streamline team development.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Qatar Olympic and Sports Museum",
        "thumbnail": "project_qatar.webp",
        "url": "https://sngular.com/success-stories/11/faster-taller-stronger-and-more-innovative",
        "date": "Feb 2021 - Oct 2022",
        "description": "Main programmer of interactive experiences for the Qatar Olympic and Sports Museum. This included 3D minigames, motion detection with Kinect and interactive panels with touchscreens.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "SABIC Digital Experience Center",
        "thumbnail": "project_sabic.webp",
        "url": "https://sabic.com/en",
        "date": "Oct 2022 - Apr 2023",
        "description": "Main programmer of multi-device interactives for the headquarters of SABIC, a leading chemical company, including interactive tables, touch screens and AR experiences.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Exhibify",
        "thumbnail": "project_exhibify.webp",
        "url": "https://exhibify.net",
        "date": "Aug 2021 - Mar 2022",
        "description": "I developed a virtual exhibition creation tool for Exhibify, a platform that allows artists to create custom exhibitions to showcase and sell their works.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Color Rush",
        "thumbnail": "project_naolito.webp",
        "url": "https://naolito.com",
        "date": "May 2022 - Jul 2022",
        "description": "I developed a prototype 2D runner mobile game commissioned by Naolito Animation Studios, which included all the main mechanics and a level editor to facilitate the creation of new levels by the Naolito team.",
        "skills": ["Unity", "C#"]
      },
      {
        "name": "Uttopion",
        "thumbnail": "project_uttopion.webp",
        "url": "https://uttopion.es",
        "date": "Feb 2021 - Dec 2021",
        "description": "I worked on incorporating multiplayer features and content updates for Uttopion, a metaverse where users can attend concerts, parties and other events in a 3D environment.",
        "skills": ["Unity", "C#", "Photon"]
      },
      {
        "name": "TodoLibros3D",
        "thumbnail": "project_todolibros3d.webp",
        "url": "https://todolibros3d.com",
        "date": "Feb 2022 - Mar 2022",
        "description": "I added multiplayer features to TodoLibros3D, a virtual library where users could now interact with each other in real time by creating their own custom avatars and via text chat.",
        "skills": ["Unity", "C#", "Photon"]
      }
    ]
  },
  "sideProjects": {
    "name": "Side Projects",
    "projects": [
      {
        "name": "GameResources.dev",
        "thumbnail": "project_gameresources.webp",
        "url": "https://gameresources.dev",
        "date": "2026",
        "description": "A directory of useful tools and resources for each field involved in game development, including code, 3D assets, marketing, or audio, among others.",
        "skills": ["Astro", "TypeScript", "HTML", "CSS"]
      },
      {
        "name": "WattLuz",
        "thumbnail": "project_wattluz.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.precioluz",
        "date": "2024",
        "description": "Mobile app to check the electricity price in Spain in real time, with interactive graphs and customizable notifications to help you save on your electricity bill.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Nanito Launcher",
        "thumbnail": "project_nanitolauncher.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.minimallauncher",
        "date": "2024",
        "description": "Minimalist launcher for Android that offers a distraction-free user experience, with a clean design and a customizable interface.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Chupito",
        "thumbnail": "project_chupito.webp",
        "url": "https://play.google.com/store/apps/details?id=com.menito.appcohol",
        "date": "2020",
        "description": "Mobile app that includes challenges and questions to liven up any party. With over 370,000 downloads, it has become one of the most popular apps in its category in several countries.",
        "skills": ["Flutter", "Dart"]
      },
      {
        "name": "Pincho.io",
        "thumbnail": "project_pinchoio.webp",
        "url": "https://youtube.com/watch?v=eDQVwSZA6f0",
        "date": "2019",
        "description": "Mobile game inspired by Agar.io, where players must attack others to grow and be the biggest in the game. The game reached +5,000 downloads on Google Play, but is currently no longer available.",
        "skills": ["Unity", "C#"]
      }
    ]
  }
}
